spring:
  data:
    rest:
      basePath: /api
  datasource:
    username: sensoric
---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost/sensoric
    password: '{cipher}AgABNCAnEd6LxtvlQ8BOkZnUpIXvTq/k9N0989cU6Eeam+BjOy8PxKB/JoWPVHzK0eswA4NTsEjBCGWu0vF8+t4EgJemNzthyVKrQQaQ0z3gpj+MlzDOWVLs0gZt7IlbNpGdz28iME2Mt+9EoZICLrKuvpzxP6ISddOH77Kd9fzqT9Aq1e5dy/yzaIQWXeW8hi5xvlTZtyn7HW+HLGDDkinwZaCZWWPtvuwTx+5VBkZu8yjEW7Fp0+ctXJ/adRiRaF47WaVFdbSh0kjQyTRv+oG4g/Novs2MSItIONxNpQ+lKUO0g4KQsd56uKCJ3PyODDmKmQDNixShKWNItHf6/KkfEKOvW0cATVDmSTgDwLaitY9/1berMHMMDncBC8H02Ax3Z+CyrZd+MZEakR3C2dmmk4JOeLfjfTPx/M2Ab27AEOg//JVzE5UOk4mj18lWK3oIt6WV27mSIVTPXXU5X/SYD08at9tRHlBdyy0l/9ZSUxMQtGoz7aE3oso7HQ2tvO9ZgtcBb+lzjMoOx4P0VzgLGLzZMXKITo2iWAAmn+9MRr2WUhKZ57Z3GN9xEwolXpKGYKApt655MoJKUAZKS4Bi+fnTCNbjHrDojuuItHjvDjfJMhnIl4PT+PsWf524qFs/NlbomV0dqFQMXQQHpVkIejWhshsZsP/SScpCb+gASyR+Zii2vkoYaey9XhfHPCjGvvTBV5DrPuxLjyozsb+x/oUMfg4Oj906LQ7mX/XCP/YK0YYImmXUmSHId59BCIU='
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://postgres/sensoric
    password: '{cipher}AgCb+1MMy1JiKkf9aP8r/NQKFaiECLRwpgqH6qB83H1XZcUl8LMgZE2T2DRyc8DwC6kaKUORFYAEtrJhmIh/1KM+QsA1n0vDxyGtNBRiZBrnzNfs2FgwpGE1rOT7AWPFYGTdx26FBo8yq7yotsCzqptYgcYZThU9fxc2dVo1nlsM7NpYsJPz8bm+ObnNiEztV64Yuxtn13KIOSF2GIHhAR3/MHtR2CDyafDPjeyQ4fBk1h0qbHr0+Uw8WE1ejOK1lz/SsU17E/cpuE+h45vxoB7OADL+PJJ6nJzlb5F1LnJ/nUSidslMX+3e+OnLpxr/jcQe4ZDT7iqGB/nBbd6jHpHYBoblpBvXRKT/SU9ptFpeBFn/XWLJWyYXOh3W8lQgH+P7Ro1thBh1LPCFHux4RBTNSx1Sd4OhjM71wAyDSDnHsNQwszB1EiBWl9FfGZjgLFb4yjAN1Kti2o4qSrcPKMKfeoHumypGl54TI8rWmPl2zwLhtReGoJThg670sKnJfeHMZJxHfXRYP0EOKfIZ2FL9zjZg0wlTCpj7Ybu/Ke0lDM/m+lHTwUWZlpPJBJbNxkXwn7FPgtmeTzvtqFelXosTRrodQ42wAbmOCeGCJEZi2/OI89x/w9fLKq9ePoQF5Z6EBTay3+Ec/3+aVwLuHBNOknD2BY+bgoEMDOQgb4fuukk1ljt+enwKJewbJ69XThLo5EQ65X3e4pE8D3cSiQyGocVCIAU+PsaTpw26TZOEff0TkFS5y9N6ARxsby3B4lU='
