spring:
  data:
    cassandra:
      cluster-name: sensoric
      keyspace-name: sensoric
---
spring:
  profiles: local
  data:
    cassandra:
      contact-points: localhost
sensoric:
  security:
    user:
      password: '{noop}readings-user'
    manager:
      password: '{noop}readings-manager'
---
spring:
  profiles: production
  data:
    cassandra:
      contact-points: cassandra