spring:
  data:
    rest:
      basePath: /api
  datasource:
    username: sensoric
---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost/sensoric
    password: '{cipher}7164d301a5994c201fd1c77326ca0de716e1c8cb79ba59ce714b772f39c085c7'
sensoric:
  security:
    user:
      password: '{noop}sensor-user'
    manager:
      password: '{noop}sensor-manager'
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://postgres/sensoric
    password: '{cipher}AgCb+1MMy1JiKkf9aP8r/NQKFaiECLRwpgqH6qB83H1XZcUl8LMgZE2T2DRyc8DwC6kaKUORFYAEtrJhmIh/1KM+QsA1n0vDxyGtNBRiZBrnzNfs2FgwpGE1rOT7AWPFYGTdx26FBo8yq7yotsCzqptYgcYZThU9fxc2dVo1nlsM7NpYsJPz8bm+ObnNiEztV64Yuxtn13KIOSF2GIHhAR3/MHtR2CDyafDPjeyQ4fBk1h0qbHr0+Uw8WE1ejOK1lz/SsU17E/cpuE+h45vxoB7OADL+PJJ6nJzlb5F1LnJ/nUSidslMX+3e+OnLpxr/jcQe4ZDT7iqGB/nBbd6jHpHYBoblpBvXRKT/SU9ptFpeBFn/XWLJWyYXOh3W8lQgH+P7Ro1thBh1LPCFHux4RBTNSx1Sd4OhjM71wAyDSDnHsNQwszB1EiBWl9FfGZjgLFb4yjAN1Kti2o4qSrcPKMKfeoHumypGl54TI8rWmPl2zwLhtReGoJThg670sKnJfeHMZJxHfXRYP0EOKfIZ2FL9zjZg0wlTCpj7Ybu/Ke0lDM/m+lHTwUWZlpPJBJbNxkXwn7FPgtmeTzvtqFelXosTRrodQ42wAbmOCeGCJEZi2/OI89x/w9fLKq9ePoQF5Z6EBTay3+Ec/3+aVwLuHBNOknD2BY+bgoEMDOQgb4fuukk1ljt+enwKJewbJ69XThLo5EQ65X3e4pE8D3cSiQyGocVCIAU+PsaTpw26TZOEff0TkFS5y9N6ARxsby3B4lU='
